{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnableToSetCallback"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/reachabilityerror\/unabletosetcallback"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ReachabilityError\/UnableToSetCallback","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnableToSetCallback"}],"title":"ReachabilityError.UnableToSetCallback","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:11DocuSignAPI17ReachabilityErrorO19UnableToSetCallbackyA2CmF","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ReachabilityError"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ReachabilityError":{"role":"symbol","title":"ReachabilityError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReachabilityError"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ReachabilityError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReachabilityError"}],"url":"\/documentation\/docusignapi\/reachabilityerror"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ReachabilityError/UnableToSetCallback":{"role":"symbol","title":"ReachabilityError.UnableToSetCallback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnableToSetCallback"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ReachabilityError\/UnableToSetCallback","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/reachabilityerror\/unabletosetcallback"}}}